### ISSUE TITLE
Sync with latest blueMSX

### ISSUE THREAD

**Issue by clobber** [pokebyte/blueMSX-Core#1]
Any chance you could update the OE core port with the latest changes from blueMSX?

**Comment by pokebyte** [comment]
Sorry for not replying to this for so long. I've been distracted with a bunch of other stuff.

I noticed commit https://github.com/OpenEmu/blueMSX-Core/commit/befa88064814b7ac08dae93f6a2ef14ab913e12c , so 
I figured I should comment.

tryLaunchUnknownFile allows DSK and CAS files to be launched, if the user replaces the C-BIOS ROMs with proper ones. Hardcoding to assume that everything's a cartridge effectively kills that ability. The point is probably moot, given that the average user doesn't know that that's possible, but still...

While we're on the subject, any idea on what needs to happen for the plugin to receive graphical assets (icons, etc..)?

**Comment by pokebyte** [comment]
So following the discussion with cyco, given the goals of OpenEmu, the solution by the commit https://github.com/OpenEmu/blueMSX-Core/commit/befa88064814b7ac08dae93f6a2ef14ab913e12c makes sense, so I'll go ahead and close this issue.

I also noticed that I completely missed the system icon that had been added. :)
